import type { BrandProfile } from "@/types/brand";

export const brandProfiles: BrandProfile[] = [
  {
    id: "nova-cosmetics",
    name: "Nova Cosmetics",
    industry: "Cosmétique & beauté",
    description:
      "Marque de cosmétiques naturels dédiée aux routines de soin simples et efficaces, pensées pour un usage quotidien.",
    productsAndServices: [
      "Soins visage naturels",
      "Gamme solaire été",
      "Maquillage minéral",
      "Box abonnement mensuelle",
    ],
    targetAudience: "Femmes et hommes de 20 à 40 ans, sensibles aux ingrédients naturels et à la transparence des marques.",
    audiencePainPoints: [],
    preferredContentTypes: [],
    preferredFormats: [],
    successMetrics: [],
    communicationGoals: [
      "Renforcer la notoriété de la nouvelle gamme été",
      "Augmenter l'engagement sur Instagram et TikTok",
      "Fidéliser la communauté existante",
    ],
    toneOfVoice: "Chaleureux, positif et complice, sans jamais être infantilisant.",
    languages: ["Français", "Anglais"],
    priorityTopics: [
      "Routine skincare",
      "Ingrédients naturels",
      "Coulisses de fabrication",
      "Avis et témoignages clients",
    ],
    topicsToAvoid: ["Comparaison directe avec des concurrents", "Promesses de résultats miracles"],
    preferredPhrases: ["Prenez soin de vous", "100% naturel", "Fabriqué en France"],
    forbiddenWords: ["Miracle", "Anti-âge garanti", "Sans défaut"],
    preferredCtas: ["Découvrez la gamme", "Testez votre routine", "Rejoignez la communauté"],
    socialPlatforms: ["instagram", "tiktok"],
    contentExamples: [
      {
        id: "nova-example-1",
        platform: "instagram",
        title: "Lancement de la nouvelle gamme été",
        excerpt: "Annonce officielle du lancement de la nouvelle gamme solaire, avec les visuels produits.",
      },
      {
        id: "nova-example-2",
        platform: "tiktok",
        title: "Routine skincare en 15 secondes",
        excerpt: "Une routine skincare condensée en 15 secondes, format vertical, musique tendance.",
      },
    ],
  },
  {
    id: "atlas-consulting",
    name: "Atlas Consulting",
    industry: "Conseil en stratégie & transformation digitale",
    description:
      "Cabinet de conseil accompagnant des entreprises retail dans leur transformation digitale.",
    productsAndServices: ["Audit digital", "Accompagnement transformation", "Formation des équipes"],
    targetAudience: "Directions générales et directions marketing d'entreprises retail de taille intermédiaire.",
    audiencePainPoints: [],
    preferredContentTypes: [],
    preferredFormats: [],
    successMetrics: [],
    communicationGoals: ["Asseoir l'expertise du cabinet", "Générer des prises de contact qualifiées"],
    toneOfVoice: "Expert, factuel, orienté résultats.",
    languages: ["Français", "Anglais"],
    priorityTopics: ["Études de cas clients", "Tendances retail", "Recrutement"],
    topicsToAvoid: [],
    preferredPhrases: ["Résultats mesurables", "Approche sur-mesure"],
    forbiddenWords: [],
    preferredCtas: ["Prenons rendez-vous", "Découvrir l'étude de cas"],
    socialPlatforms: ["linkedin", "x"],
    contentExamples: [
      {
        id: "atlas-example-1",
        platform: "linkedin",
        title: "Étude de cas : transformation digitale d'un client retail",
        excerpt: "Comment nous avons accompagné un acteur du retail dans sa transformation digitale sur 6 mois.",
      },
    ],
  },
  {
    id: "le-comptoir-bio",
    name: "Le Comptoir Bio",
    industry: "Alimentation biologique",
    description: "Réseau de boutiques de produits alimentaires biologiques et locaux.",
    productsAndServices: [],
    targetAudience: "",
    audiencePainPoints: [],
    preferredContentTypes: [],
    preferredFormats: [],
    successMetrics: [],
    communicationGoals: [],
    toneOfVoice: "",
    languages: ["Français"],
    priorityTopics: [],
    topicsToAvoid: [],
    preferredPhrases: [],
    forbiddenWords: [],
    preferredCtas: [],
    socialPlatforms: ["facebook"],
    contentExamples: [],
  },
];
