import type { PerformanceMetric, SocialAccount } from "@/types/dashboard";
import type { Publication } from "@/types/publication";

const CREATED_OFFSET_DAYS = 5;

function daysBefore(isoDateTime: string, days: number): string {
  const [datePart, timePart] = isoDateTime.split("T");
  const date = new Date(`${datePart}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() - days);
  return `${date.toISOString().slice(0, 10)}T${timePart}`;
}

const CAMPAIGN_BY_POST_ID: Record<string, string> = {
  "post-11": "campaign-nova-summer-launch",
  "post-18": "campaign-nova-summer-sale",
  "post-19": "campaign-atlas-roundtable-q3",
};

export const performanceMetrics: PerformanceMetric[] = [
  { id: "impressions", label: "Impressions", value: "128 400", change: 12.4 },
  { id: "engagement", label: "Taux d'engagement", value: "4.8%", change: 1.6 },
  { id: "followers", label: "Nouveaux abonnés", value: "1 042", change: 8.1 },
  { id: "clicks", label: "Clics sur les liens", value: "3 210", change: -2.3 },
];

const STANDARD_PERMISSIONS = [
  "Lecture du profil",
  "Publication de contenu",
  "Lecture des statistiques",
  "Gestion des commentaires",
];

export const connectedAccounts: SocialAccount[] = [
  {
    id: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    accountName: "Nova Cosmetics",
    handle: "@novacosmetics",
    status: "connected",
    lastSyncedAt: "2026-07-23T08:00:00",
    permissions: STANDARD_PERMISSIONS,
  },
  {
    id: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    accountName: "Le Comptoir Bio",
    handle: "lecomptoirbio",
    status: "connected",
    lastSyncedAt: "2026-07-22T14:30:00",
    permissions: STANDARD_PERMISSIONS,
  },
  {
    id: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    accountName: "Atlas Consulting",
    handle: "company/atlas-consulting",
    status: "syncing",
    lastSyncedAt: "2026-07-24T07:15:00",
    permissions: ["Lecture du profil", "Publication de contenu"],
  },
  {
    id: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    accountName: "Nova Cosmetics",
    handle: "@novacosmetics",
    status: "expired",
    lastSyncedAt: "2026-07-10T09:00:00",
    permissions: ["Lecture du profil", "Publication de contenu", "Lecture des statistiques"],
  },
  {
    id: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    accountName: "Atlas Consulting",
    handle: "@atlasconsulting",
    status: "error",
    lastSyncedAt: "2026-07-20T16:45:00",
    permissions: ["Lecture du profil", "Publication de contenu"],
  },
  {
    id: "acc-6",
    platform: "youtube",
    brand: "Nova Cosmetics",
    accountName: "Nova Cosmetics",
    handle: "@NovaCosmeticsOfficial",
    status: "disconnected",
    lastSyncedAt: null,
    permissions: [],
  },
];

const NOVA_HASHTAGS = ["#NovaCosmetics", "#SkincareRoutine", "#BeautéNaturelle"];
const ATLAS_HASHTAGS = ["#AtlasConsulting", "#TransformationDigitale", "#Retail"];
const COMPTOIR_HASHTAGS = ["#LeComptoirBio", "#Bio", "#ProduitsLocaux"];

const rawPosts: Publication[] = [
  {
    id: "post-1",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-02T09:00:00",
    timeZone: "America/Toronto",
    theme: "Actualité du secteur",
    format: "text",
    objective: "Engager la communauté sur les temps forts du trimestre",
    excerpt: "Nos vœux pour le nouveau trimestre",
    text: "Retour sur les objectifs du trimestre et les grandes étapes à venir pour nos clients retail.",
    cta: "Échangeons sur vos priorités",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [],
    status: "scheduled",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-2",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-05T11:00:00",
    timeZone: "America/Toronto",
    theme: "Point de vue d'expert",
    format: "text",
    objective: "Asseoir la crédibilité des consultants",
    excerpt: "Thread : les erreurs courantes en stratégie de contenu",
    text: "Un thread en 6 tweets sur les erreurs les plus fréquentes observées chez nos clients cette année.",
    cta: "Partagez votre expérience en commentaire",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [],
    status: "draft",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-3",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-08T10:00:00",
    timeZone: "America/Toronto",
    theme: "Coulisses de fabrication",
    format: "carousel",
    objective: "Humaniser la marque et montrer l'envers du décor",
    excerpt: "Coulisses de notre dernier shooting",
    text: "Une série de photos behind-the-scenes du shooting produit de la semaine dernière, avec l'équipe créative.",
    cta: "Swipez pour voir la suite",
    hashtags: NOVA_HASHTAGS,
    firstComment: "Merci à toute l'équipe pour cette journée !",
    media: [
      { id: "post-3-media-1", type: "image", label: "shooting-01.jpg" },
      { id: "post-3-media-2", type: "image", label: "shooting-02.jpg" },
    ],
    status: "in_review",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "En attente de validation des droits image de l'équipe.",
    comments: [
      {
        id: "post-3-comment-1",
        authorName: "Camille Dubois",
        audience: "internal",
        text: "@Julien Marchand peux-tu valider les droits image de l'équipe avant publication ?",
        createdAt: "2026-07-06T11:20:00",
      },
    ],
    history: [
      { id: "post-3-history-1", action: "Créée", actorName: "Camille Dubois", createdAt: "2026-07-05T09:00:00" },
      {
        id: "post-3-history-2",
        action: "Envoyée en révision",
        actorName: "Camille Dubois",
        createdAt: "2026-07-06T11:15:00",
      },
    ],
  },
  {
    id: "post-4",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    scheduledFor: "2026-07-15T10:00:00",
    timeZone: "America/Toronto",
    theme: "Vie du magasin",
    format: "image",
    objective: "Informer la clientèle des nouveaux horaires",
    excerpt: "Nouveaux horaires d'été",
    text: "Annonce des nouveaux horaires d'ouverture estivaux pour toutes nos boutiques partenaires.",
    cta: "Retrouvez tous nos horaires en bio",
    hashtags: COMPTOIR_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-4-media-1", type: "image", label: "horaires-ete.jpg" }],
    status: "scheduled",
    owner: "Léa Fontaine",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-5",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-16T09:00:00",
    timeZone: "America/Toronto",
    theme: "Étude de cas client",
    format: "carousel",
    objective: "Démontrer la valeur ajoutée du conseil sur un cas concret",
    excerpt: "Étude de cas : transformation digitale d'un client retail",
    text: "Comment nous avons accompagné un acteur du retail dans sa transformation digitale sur 6 mois, avec des résultats chiffrés.",
    cta: "Découvrez l'étude de cas complète",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-5-media-1", type: "image", label: "etude-cas-slide-1.png" }],
    status: "approved",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-6",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-16T15:00:00",
    timeZone: "America/Toronto",
    theme: "Question à la communauté",
    format: "text",
    objective: "Recueillir des insights pour la prochaine étude sectorielle",
    excerpt: "Sondage : quel canal préférez-vous ?",
    text: "Un sondage rapide auprès de notre communauté pour orienter notre prochaine étude sectorielle.",
    cta: "Votez et commentez",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [],
    status: "pending_client",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "En attente de retour client sur la formulation du sondage.",
    comments: [
      {
        id: "post-6-comment-1",
        authorName: "Sami Nasri",
        audience: "client",
        text: "@Nadia Kader voici le sondage proposé pour la prochaine étude sectorielle, qu'en pensez-vous ?",
        createdAt: "2026-07-14T10:00:00",
      },
    ],
    history: [
      { id: "post-6-history-1", action: "Créée", actorName: "Sami Nasri", createdAt: "2026-07-12T09:00:00" },
      {
        id: "post-6-history-2",
        action: "Envoyée au client",
        actorName: "Sami Nasri",
        createdAt: "2026-07-14T10:00:00",
      },
    ],
  },
  {
    id: "post-7",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-18T08:00:00",
    timeZone: "America/Toronto",
    theme: "Conseils pratiques",
    format: "carousel",
    objective: "Créer de la proximité et de l'utilité perçue au quotidien",
    excerpt: "Tuto maquillage estival",
    text: "Un tutoriel pas à pas pour un maquillage lumineux adapté aux journées d'été.",
    cta: "Testez ce look et taguez-nous",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [
      { id: "post-7-media-1", type: "image", label: "tuto-maquillage-1.jpg" },
      { id: "post-7-media-2", type: "image", label: "tuto-maquillage-2.jpg" },
    ],
    status: "scheduled",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-8",
    accountId: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-18T12:00:00",
    timeZone: "America/Toronto",
    theme: "Routine skincare",
    format: "short_video",
    objective: "Renforcer l'expertise perçue sur les ingrédients",
    excerpt: "Routine skincare en 15 secondes",
    text: "Une routine skincare condensée en 15 secondes, format vertical, musique tendance.",
    cta: "Abonnez-vous pour la suite",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-8-media-1", type: "video", label: "routine-skincare.mp4" }],
    status: "in_production",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "Montage vidéo en cours chez le prestataire.",
    comments: [],
    history: [],
  },
  {
    id: "post-9",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    scheduledFor: "2026-07-18T19:00:00",
    timeZone: "America/Toronto",
    theme: "Rencontre producteur",
    format: "short_video",
    objective: "Valoriser les partenaires producteurs locaux",
    excerpt: "Rencontre avec un producteur local",
    text: "Portrait vidéo d'un de nos producteurs partenaires et de ses méthodes de culture biologique.",
    cta: "Découvrez notre sélection de saison",
    hashtags: COMPTOIR_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-9-media-1", type: "video", label: "portrait-producteur.mp4" }],
    status: "scheduled",
    owner: "Léa Fontaine",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-10",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-22T16:00:00",
    timeZone: "America/Toronto",
    theme: "Actualité du secteur",
    format: "text",
    objective: "Toucher un public dans un autre fuseau horaire",
    excerpt: "Rappel : notre publication d'hier",
    text: "Un rappel amical du contenu publié la veille, pour toucher un public dans un autre fuseau horaire.",
    cta: "Relisez notre analyse",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [],
    status: "published",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-11",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-24T09:00:00",
    timeZone: "America/Toronto",
    theme: "Offre et appel à l'action",
    format: "image",
    objective: "Générer des ventes directes sur la gamme du moment",
    excerpt: "Lancement de la nouvelle gamme été",
    text: "Annonce officielle du lancement de la nouvelle gamme solaire, avec les visuels produits et les ingrédients clés.",
    cta: "Découvrez la gamme",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-11-media-1", type: "image", label: "gamme-ete-hero.jpg" }],
    status: "scheduled",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-12",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-24T14:30:00",
    timeZone: "America/Toronto",
    theme: "Recrutement / vie du cabinet",
    format: "text",
    objective: "Attirer des talents et humaniser la marque",
    excerpt: "Recrutement : nous cherchons un consultant senior",
    text: "Publication d'offre d'emploi pour renforcer notre équipe conseil retail sur le second semestre.",
    cta: "Postulez ou partagez",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [],
    status: "in_review",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [
      {
        id: "post-12-comment-1",
        authorName: "Sami Nasri",
        audience: "internal",
        text: "@Nadia Kader l'offre est prête à être relue avant diffusion, dites-moi si le ton vous convient.",
        createdAt: "2026-07-23T09:30:00",
      },
    ],
    history: [
      { id: "post-12-history-1", action: "Créée", actorName: "Sami Nasri", createdAt: "2026-07-22T09:00:00" },
      {
        id: "post-12-history-2",
        action: "Envoyée en révision",
        actorName: "Sami Nasri",
        createdAt: "2026-07-23T09:30:00",
      },
    ],
  },
  {
    id: "post-13",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-24T18:00:00",
    timeZone: "America/Toronto",
    theme: "Témoignages clients",
    format: "story",
    objective: "Rassurer via la preuve sociale",
    excerpt: "Story : avis clients",
    text: "Compilation de témoignages clients reçus cette semaine sur la nouvelle gamme.",
    cta: "Partagez votre avis en story",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-13-media-1", type: "image", label: "avis-clients-story.jpg" }],
    status: "draft",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-14",
    accountId: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-26T11:00:00",
    timeZone: "America/Toronto",
    theme: "Routine skincare",
    format: "carousel",
    objective: "Décliner le contenu vidéo en format carrousel",
    excerpt: "Routine skincare en 15 secondes",
    text: "Variante courte de la routine skincare, adaptée au format carrousel.",
    cta: "Enregistrez ce post",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [],
    status: "idea",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-15",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    scheduledFor: "2026-07-27T17:00:00",
    timeZone: "America/Toronto",
    theme: "Recette de saison",
    format: "image",
    objective: "Mettre en avant les produits phares de la sélection",
    excerpt: "Recette de saison avec nos produits locaux",
    text: "Recette d'été mettant en avant trois produits phares de notre sélection de saison.",
    cta: "Retrouvez la recette complète en boutique",
    hashtags: COMPTOIR_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-15-media-1", type: "image", label: "recette-ete.jpg" }],
    status: "scheduled",
    owner: "Léa Fontaine",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-16",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    scheduledFor: "2026-07-29T08:30:00",
    timeZone: "America/Toronto",
    theme: "Point de vue d'expert",
    format: "text",
    objective: "Positionner le cabinet en veille active",
    excerpt: "Thread : 5 tendances marketing pour 2026",
    text: "Notre analyse des 5 tendances marketing à surveiller sur la fin d'année 2026.",
    cta: "Lisez le thread complet",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [],
    status: "scheduled",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-17",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    scheduledFor: "2026-07-31T09:00:00",
    timeZone: "America/Toronto",
    theme: "Bilan mensuel",
    format: "carousel",
    objective: "Remercier la communauté et valoriser les temps forts",
    excerpt: "Bilan du mois en images",
    text: "Un récap en carrousel des temps forts du mois avec la communauté.",
    cta: "Merci de votre fidélité",
    hashtags: COMPTOIR_HASHTAGS,
    firstComment: "",
    media: [
      { id: "post-17-media-1", type: "image", label: "bilan-mois-1.jpg" },
      { id: "post-17-media-2", type: "image", label: "bilan-mois-2.jpg" },
    ],
    status: "failed",
    owner: "Léa Fontaine",
    approver: "Julien Marchand",
    internalNotes: "Échec de publication : dimensions du carrousel non conformes, à reformater.",
    comments: [],
    history: [],
  },
  {
    id: "post-18",
    accountId: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-07-31T14:00:00",
    timeZone: "America/Toronto",
    theme: "Offre et appel à l'action",
    format: "short_video",
    objective: "Maximiser l'engagement sur la fin de la gamme été",
    excerpt: "Défi beauté de fin de mois",
    text: "Lancement d'un défi communautaire autour de la gamme été, avec appel à participation.",
    cta: "Participez au défi",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-18-media-1", type: "video", label: "defi-beaute.mp4" }],
    status: "scheduled",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-19",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    scheduledFor: "2026-08-03T10:00:00",
    timeZone: "America/Toronto",
    theme: "Événement",
    format: "image",
    objective: "Générer des inscriptions à l'événement",
    excerpt: "Prochaine table ronde clients",
    text: "Invitation à notre table ronde trimestrielle avec trois clients retail invités.",
    cta: "Inscrivez-vous à la table ronde",
    hashtags: ATLAS_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-19-media-1", type: "image", label: "table-ronde-visuel.jpg" }],
    status: "scheduled",
    owner: "Sami Nasri",
    approver: "Nadia Kader",
    internalNotes: "",
    comments: [],
    history: [],
  },
  {
    id: "post-20",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    scheduledFor: "2026-06-28T09:00:00",
    timeZone: "America/Toronto",
    theme: "Témoignages clients",
    format: "carousel",
    objective: "Valoriser le bilan d'une collaboration influenceuse",
    excerpt: "Retour sur notre collaboration influenceuse",
    text: "Bilan chiffré de la dernière collaboration avec une créatrice de contenu beauté.",
    cta: "Découvrez les coulisses de la collab",
    hashtags: NOVA_HASHTAGS,
    firstComment: "",
    media: [{ id: "post-20-media-1", type: "image", label: "collab-influenceuse-1.jpg" }],
    status: "published",
    owner: "Camille Dubois",
    approver: "Julien Marchand",
    internalNotes: "",
    comments: [],
    history: [],
  },
];

export const posts: Publication[] = rawPosts.map((post) => ({
  ...post,
  source: "manual",
  campaignId: CAMPAIGN_BY_POST_ID[post.id],
  createdAt: daysBefore(post.scheduledFor, CREATED_OFFSET_DAYS),
  updatedAt:
    post.history.length > 0
      ? post.history[post.history.length - 1].createdAt
      : daysBefore(post.scheduledFor, CREATED_OFFSET_DAYS),
}));
