import type { PerformanceMetric, ScheduledPost, SocialAccount } from "@/types/dashboard";

export const performanceMetrics: PerformanceMetric[] = [
  { id: "impressions", label: "Impressions", value: "128 400", change: 12.4 },
  { id: "engagement", label: "Taux d'engagement", value: "4.8%", change: 1.6 },
  { id: "followers", label: "Nouveaux abonnés", value: "1 042", change: 8.1 },
  { id: "clicks", label: "Clics sur les liens", value: "3 210", change: -2.3 },
];

export const connectedAccounts: SocialAccount[] = [
  { id: "acc-1", platform: "instagram", brand: "Nova Cosmetics", handle: "@novacosmetics", status: "connected" },
  { id: "acc-2", platform: "facebook", brand: "Le Comptoir Bio", handle: "Le Comptoir Bio", status: "connected" },
  { id: "acc-3", platform: "linkedin", brand: "Atlas Consulting", handle: "Atlas Consulting", status: "connected" },
  { id: "acc-4", platform: "tiktok", brand: "Nova Cosmetics", handle: "@novacosmetics", status: "reconnect_needed" },
  { id: "acc-5", platform: "x", brand: "Atlas Consulting", handle: "@atlasconsulting", status: "connected" },
];

export const posts: ScheduledPost[] = [
  {
    id: "post-1",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    excerpt: "Nos vœux pour le nouveau trimestre",
    content:
      "Retour sur les objectifs du trimestre et les grandes étapes à venir pour nos clients retail.",
    scheduledFor: "2026-07-02T09:00:00",
    status: "scheduled",
  },
  {
    id: "post-2",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    excerpt: "Thread : les erreurs courantes en stratégie de contenu",
    content:
      "Un thread en 6 tweets sur les erreurs les plus fréquentes observées chez nos clients cette année.",
    scheduledFor: "2026-07-05T11:00:00",
    status: "draft",
  },
  {
    id: "post-3",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    excerpt: "Coulisses de notre dernier shooting",
    content:
      "Une série de photos behind-the-scenes du shooting produit de la semaine dernière, avec l'équipe créative.",
    scheduledFor: "2026-07-08T10:00:00",
    status: "pending_approval",
  },
  {
    id: "post-4",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    excerpt: "Nouveaux horaires d'été",
    content: "Annonce des nouveaux horaires d'ouverture estivaux pour toutes nos boutiques partenaires.",
    scheduledFor: "2026-07-15T10:00:00",
    status: "scheduled",
  },
  {
    id: "post-5",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    excerpt: "Étude de cas : transformation digitale d'un client retail",
    content:
      "Comment nous avons accompagné un acteur du retail dans sa transformation digitale sur 6 mois, avec des résultats chiffrés.",
    scheduledFor: "2026-07-16T09:00:00",
    status: "scheduled",
  },
  {
    id: "post-6",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    excerpt: "Sondage : quel canal préférez-vous ?",
    content: "Un sondage rapide auprès de notre communauté pour orienter notre prochaine étude sectorielle.",
    scheduledFor: "2026-07-16T15:00:00",
    status: "pending_approval",
  },
  {
    id: "post-7",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    excerpt: "Tuto maquillage estival",
    content: "Un tutoriel pas à pas pour un maquillage lumineux adapté aux journées d'été.",
    scheduledFor: "2026-07-18T08:00:00",
    status: "scheduled",
  },
  {
    id: "post-8",
    accountId: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    excerpt: "Routine skincare en 15 secondes",
    content: "Une routine skincare condensée en 15 secondes, format vertical, musique tendance.",
    scheduledFor: "2026-07-18T12:00:00",
    status: "draft",
  },
  {
    id: "post-9",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    excerpt: "Rencontre avec un producteur local",
    content: "Portrait vidéo d'un de nos producteurs partenaires et de ses méthodes de culture biologique.",
    scheduledFor: "2026-07-18T19:00:00",
    status: "scheduled",
  },
  {
    id: "post-10",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    excerpt: "Rappel : notre publication d'hier",
    content: "Un rappel amical du contenu publié la veille, pour toucher un public dans un autre fuseau horaire.",
    scheduledFor: "2026-07-22T16:00:00",
    status: "scheduled",
  },
  {
    id: "post-11",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    excerpt: "Lancement de la nouvelle gamme été",
    content:
      "Annonce officielle du lancement de la nouvelle gamme solaire, avec les visuels produits et les ingrédients clés.",
    scheduledFor: "2026-07-24T09:00:00",
    status: "scheduled",
  },
  {
    id: "post-12",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    excerpt: "Recrutement : nous cherchons un consultant senior",
    content: "Publication d'offre d'emploi pour renforcer notre équipe conseil retail sur le second semestre.",
    scheduledFor: "2026-07-24T14:30:00",
    status: "pending_approval",
  },
  {
    id: "post-13",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    excerpt: "Story : avis clients",
    content: "Compilation de témoignages clients reçus cette semaine sur la nouvelle gamme.",
    scheduledFor: "2026-07-24T18:00:00",
    status: "draft",
  },
  {
    id: "post-14",
    accountId: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    excerpt: "Routine skincare en 15 secondes",
    content: "Variante courte de la routine skincare, adaptée au format carrousel.",
    scheduledFor: "2026-07-26T11:00:00",
    status: "draft",
  },
  {
    id: "post-15",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    excerpt: "Recette de saison avec nos produits locaux",
    content: "Recette d'été mettant en avant trois produits phares de notre sélection de saison.",
    scheduledFor: "2026-07-27T17:00:00",
    status: "scheduled",
  },
  {
    id: "post-16",
    accountId: "acc-5",
    platform: "x",
    brand: "Atlas Consulting",
    excerpt: "Thread : 5 tendances marketing pour 2026",
    content: "Notre analyse des 5 tendances marketing à surveiller sur la fin d'année 2026.",
    scheduledFor: "2026-07-29T08:30:00",
    status: "scheduled",
  },
  {
    id: "post-17",
    accountId: "acc-2",
    platform: "facebook",
    brand: "Le Comptoir Bio",
    excerpt: "Bilan du mois en images",
    content: "Un récap en carrousel des temps forts du mois avec la communauté.",
    scheduledFor: "2026-07-31T09:00:00",
    status: "scheduled",
  },
  {
    id: "post-18",
    accountId: "acc-4",
    platform: "tiktok",
    brand: "Nova Cosmetics",
    excerpt: "Défi beauté de fin de mois",
    content: "Lancement d'un défi communautaire autour de la gamme été, avec appel à participation.",
    scheduledFor: "2026-07-31T14:00:00",
    status: "scheduled",
  },
  {
    id: "post-19",
    accountId: "acc-3",
    platform: "linkedin",
    brand: "Atlas Consulting",
    excerpt: "Prochaine table ronde clients",
    content: "Invitation à notre table ronde trimestrielle avec trois clients retail invités.",
    scheduledFor: "2026-08-03T10:00:00",
    status: "scheduled",
  },
  {
    id: "post-20",
    accountId: "acc-1",
    platform: "instagram",
    brand: "Nova Cosmetics",
    excerpt: "Retour sur notre collaboration influenceuse",
    content: "Bilan chiffré de la dernière collaboration avec une créatrice de contenu beauté.",
    scheduledFor: "2026-06-28T09:00:00",
    status: "scheduled",
  },
];
