import type { Theme } from "@/types/theme";

const SEED_CREATED_AT = "2026-01-01T00:00:00.000Z";

export const themes: Theme[] = [
  {
    id: "theme-nova-1",
    brandId: "nova-cosmetics",
    label: "Conseils pratiques",
    objective: "Créer de la proximité et de l'utilité perçue au quotidien",
    weekdays: ["monday"],
    order: 0,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-nova-2",
    brandId: "nova-cosmetics",
    label: "Contenu éducatif",
    objective: "Renforcer l'expertise perçue sur les ingrédients et la formulation",
    weekdays: ["tuesday"],
    order: 1,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-nova-3",
    brandId: "nova-cosmetics",
    label: "Opinion ou expertise",
    objective: "Humaniser la marque à travers un point de vue assumé",
    weekdays: ["wednesday"],
    order: 2,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-nova-4",
    brandId: "nova-cosmetics",
    label: "Démonstration ou étude de cas",
    objective: "Prouver l'efficacité produit par la preuve sociale",
    weekdays: ["thursday"],
    order: 3,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-nova-5",
    brandId: "nova-cosmetics",
    label: "Offre et appel à l'action",
    objective: "Générer des ventes directes sur la gamme du moment",
    weekdays: ["friday"],
    order: 4,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-atlas-1",
    brandId: "atlas-consulting",
    label: "Actualité du secteur",
    objective: "Positionner le cabinet en veille active",
    weekdays: ["monday"],
    order: 0,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-atlas-2",
    brandId: "atlas-consulting",
    label: "Étude de cas client",
    objective: "Démontrer la valeur ajoutée du conseil sur un cas concret",
    weekdays: ["tuesday"],
    order: 1,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-atlas-3",
    brandId: "atlas-consulting",
    label: "Point de vue d'expert",
    objective: "Asseoir la crédibilité des consultants",
    weekdays: ["thursday"],
    order: 2,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-atlas-4",
    brandId: "atlas-consulting",
    label: "Recrutement / vie du cabinet",
    objective: "Attirer des talents et humaniser la marque",
    weekdays: ["friday"],
    order: 3,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
  {
    id: "theme-comptoir-1",
    brandId: "le-comptoir-bio",
    label: "Produit du moment",
    objective: "",
    weekdays: ["monday"],
    order: 0,
    active: true,
    createdAt: SEED_CREATED_AT,
  },
];
